name: Vega UniSearch Runner

on:
  schedule:
    - cron: "45 13 * * 1-5"   # 13:45 UTC ≈ 6:45 AM PT weekdays
  workflow_dispatch: {}      # manual run

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip pyyaml
      - name: Run Vega UniSearch (skeleton)
        run: |
          python scripts/vega_unisearch_runner.py --region US --profile SmartMoney_NA_Level2
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vega-unisearch-output
          path: outputs/
