name: Deploy to Render (via Deploy Hook)

on:
  push:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          echo "Triggering Render deploy via hook..."
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"
