# One event per line. Dates are local to the event's country; output is UTC-stamped.
# importance: low | medium | high
- date: 2025-09-02
  region: US
  event: ISM Manufacturing PMI
  importance: high

- date: 2025-09-03
  region: CA
  event: Bank of Canada Rate Decision
  importance: high

- date: 2025-09-05
  region: US
  event: Nonfarm Payrolls (NFP)
  importance: high

- date: 2025-09-10
  region: MX
  event: Mexico Inflation (CPI)
  importance: medium

- date: 2025-09-12
  region: BR
  event: Brazil IPCA Inflation
  importance: medium
