version: 1
language_default: "en"            # you speak → English; partner → Spanish
timezone: "America/Mazatlan"
risk_rules:
  min_rr: 3.0
  risk_per_trade_pct: 0.50
  no_buys_within_earnings_days: 30
options_rules:
  pop_target: 0.60
  dte_window: [21, 90]
  selection_rule: "calls/call-spreads when options underpriced; puts/put-spreads when overpriced; else stock"
alerts_policy:
  mode: "yaml-first"              # only promote essentials to live autos
  live_max: 3
  promotion_limit: 2
reporting:
  morning_briefing_time_local: "06:00"
  weekly_macro_day_local: "Sunday"
notes:
  - "Keep contras/hedges hidden unless risk-off (VIX≥20 or SPY<50dma or breadth<45%)."
