name: Precheck
description: Fast guardrail (skip instead of failing)

inputs:
  vega_actions_enabled:
    description: Master on/off flag passed from workflow (vars.VEGA_ACTIONS_ENABLED). Defaults to "true".
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - shell: bash
      id: p
      env:
        # The workflow passes this input; default is "true" if the repo var is unset.
        VEGA_ACTIONS_ENABLED: ${{ inputs.vega_actions_enabled }}
      run: |
        set -e
        missing=()
        need() { [ -n "${!1}" ] || missing+=("$1"); }

        # Require only the token (pass it from the workflow via env:)
        need GITHUB_TOKEN

        if [ "${#missing[@]}" -gt 0 ]; then
          echo "::notice title=Precheck::Missing -> ${missing[*]}"
          echo "ok=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        if [ "${VEGA_ACTIONS_ENABLED}" != "true" ]; then
          echo "::notice title=Precheck::VEGA_ACTIONS_ENABLED=false (skipping)"
          echo "ok=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "ok=true" >> "$GITHUB_OUTPUT"
