name: Precheck
description: Fast guardrail (skip instead of failing)

inputs:
  vega_actions_enabled:
    description: Master on/off flag passed from workflow (vars.VEGA_ACTIONS_ENABLED). Defaults to "true".
    required: false
    default: "true"

outputs:
  ok:
    description: "String 'true' or 'false' to gate downstream jobs"
    value: ${{ steps.gate.outputs.ok }}

runs:
  using: "composite"
  steps:
    - id: gate
      shell: bash
      env:
        VEGA_ACTIONS_ENABLED: ${{ inputs.vega_actions_enabled }}
      run: |
        set -e

        # Global enable/disable flag
        if [ "${VEGA_ACTIONS_ENABLED}" != "true" ]; then
          echo "::notice title=Precheck::VEGA_ACTIONS_ENABLED=false (skipping)"
          echo "ok=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # If we get here, we're good to run
        echo "ok=true" >> "$GITHUB_OUTPUT"
