name: Precheck
description: Fast guardrail for required secrets/flags. Skips instead of failing.
runs:
  using: "composite"
  steps:
    - shell: bash
      id: p
      run: |
        missing=()
        need() { test -n "${!1}" || missing+=("$1"); }

        # 👉 Keep only what you actually use. Remove any you don't need.
        need GITHUB_TOKEN
        need RENDER_API_KEY
        need TV_COOKIES
        need SENDGRID_API_KEY

        # Global on/off switch via repo variable
        : "${VEGA_ACTIONS_ENABLED:=true}"

        if [ "${#missing[@]}" -gt 0 ]; then
          echo "::notice title=Precheck::Missing secrets -> ${missing[*]}"
          echo "ok=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        if [ "$VEGA_ACTIONS_ENABLED" != "true" ]; then
          echo "::notice title=Precheck::VEGA_ACTIONS_ENABLED=false (skipping)"
          echo "ok=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        echo "ok=true" >> "$GITHUB_OUTPUT"
