name: Add Journal Entry

on:
  push:
    branches: [ main ]

  workflow_dispatch:   # manual trigger from Actions tab

jobs:
  add_journal_entry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements-actions.txt
      - name: Run journal entry script
        run: python scripts/add_journal_entry.py
