name: Nightly Archive Snapshots

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 8 * * *'   # 01:00 PT approximate
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: vega-data
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Archive snapshots
        run: |
          python workers/snapshots/archive_snapshots.py
      - name: Commit archive
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add data/archive
          git commit -m "archive: daily snapshots $(date -u +%FT%TZ)" || echo "no changes"
          git push origin vega-data
