name: CI - Vega Smoke (Lean)
true:
  push:
    branches:
    - main
    paths:
    - app.py
    - modules/**
    - services/**
    - scripts/smoke_check.py
    - requirements.txt
    - .streamlit/**
    - '!docs/**'
    - '!assets/**'
  workflow_dispatch: null
concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true
jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.p.outputs.ok }}
    steps:
    - uses: actions/checkout@v4
    - id: p
      uses: ./.github/actions/precheck
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Install minimal deps (skip heavy extras)
      run: 'if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        '
    - name: Static import test
      run: 'python scripts/smoke_check.py

        '
    needs: precheck
    if: ${{ needs.precheck.outputs.ok == 'true' && github.ref == 'refs/heads/main'
      }}
