name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip ruff
      - run: ruff check .
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: echo "Build OK"

  notify:
    name: Send consolidated status email
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: always()   # send one email per run, even on failure
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install mail dep
        run: python -m pip install --upgrade pip sendgrid==6.11.0
      - name: Compose & send status email
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          ALERTS_FROM: ${{ secrets.ALERTS_FROM }}
          ALERTS_TO:   ${{ secrets.ALERTS_TO }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_LINT:  ${{ needs.lint.result }}
          JOB_BUILD: ${{ needs.build.result }}
        run: |
          python scripts/notify_email.py
