name: CI
on:
  push: { branches: [ "main", "develop" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install
        run: |
          pip install -r requirements.txt
      - name: Import smoke test
        run: |
          python - << 'PY'
import importlib
for m in ["streamlit","pandas","pydantic","yaml","plotly","numpy"]:
    importlib.import_module(m)
print("OK")
PY
