name: Daily Digest
true:
  push:
    branches:
    - main
  schedule:
  - cron: 15 20 * * 1-5
  workflow_dispatch: null
jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.p.outputs.ok }}
    steps:
    - uses: actions/checkout@v4
    - id: p
      uses: ./.github/actions/precheck
  digest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build digest
      id: d
      run: "TS=$(date -u +%F)\necho \"title=Daily Digest \u2014 $TS\" >> $GITHUB_OUTPUT\n\
        printf \"%s\\n\" \"# Daily Digest \u2014 $TS UTC\" > digest.md\necho \"- Morning\
        \ Report: artifact \\`morning-report\\`\" >> digest.md\necho \"- Color Guard:\
        \ artifact \\`color-guard\\`\" >> digest.md\necho \"- PDH/PDL pivots: artifact\
        \ \\`pivots\\`\" >> digest.md\necho \"- Exposure: artifact \\`exposure\\`\"\
        \ >> digest.md\n"
    - uses: actions/github-script@v7
      with:
        script: "const fs = require('fs');\nconst body = fs.readFileSync('digest.md','utf8');\n\
          await github.rest.issues.create({\n  owner: context.repo.owner, repo: context.repo.repo,\n\
          \  title: \"${{ steps.d.outputs.title }}\",\n  body, labels: ['daily','report']\n\
          });\n"
    needs: precheck
    if: ${{ needs.precheck.outputs.ok == 'true' && github.ref == 'refs/heads/main'
      }}
