name: Deploy to Render (Hook)

on:
  push:
    branches: [ main ]
    paths:
      - 'app.py'
      - 'modules/**'
      - 'services/**'
      - 'requirements.txt'
      - 'Procfile'
      - 'render.yaml'
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Trigger Render deploy
        run: curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
