name: alerts-digest
on:
  workflow_dispatch:
    inputs:
      lookback:
        description: "e.g., 1d, 4h"
        required: false
        default: "1d"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements-actions.txt
      - env:
          DIGEST_LOOKBACK: ${{ github.event.inputs.lookback }}
          ALERTS_TO: ${{ secrets.ALERTS_TO }}
        run: python -m alerts.digest
