name: Econ Calendar (Weekly)
on:
  schedule: [{ cron: "0 14 * * 1" }]  # Mon 07:00 Phoenix
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python - << 'PY'
          import yaml, json, datetime as dt, os
          data=yaml.safe_load(open("config/econ_calendar.yaml"))
          today=dt.date.today(); next7=today+dt.timedelta(days=7)
          week=[e for e in data if today.isoformat()<=e["date"]<=next7.isoformat()]
          os.makedirs("snapshots", exist_ok=True)
          open("snapshots/econ_week.json","w").write(json.dumps(week, indent=2))
          PY
      - uses: actions/upload-artifact@v4
        with: { name: econ-week, path: snapshots/econ_week.json, retention-days: 7 }
