name: Exposure Guard
true:
  push:
    branches:
    - main
  schedule:
  - cron: 30 13 * * 1-5
  workflow_dispatch: null
jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.p.outputs.ok }}
    steps:
    - uses: actions/checkout@v4
    - id: p
      uses: ./.github/actions/precheck
  exposure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: "python - << 'PY'\nimport csv, json, os\nfrom collections import defaultdict\n\
        if not os.path.exists(\"data/positions.csv\"):\n    print(\"No positions.csv;\
        \ skipping.\"); exit(0)\nrows=list(csv.DictReader(open(\"data/positions.csv\"\
        )))\ntotal=sum(float(r[\"qty\"])*float(r[\"price\"]) for r in rows if r[\"\
        qty\"] and r[\"price\"])\nbx=defaultdict(float); cx=defaultdict(float); tx=defaultdict(float)\n\
        for r in rows:\n    v=float(r[\"qty\"])*float(r[\"price\"])\n    bx[r[\"sector\"\
        ]]+=v; cx[r[\"country\"]]+=v; tx[r[\"type\"]]+=v\ndef pctmap(d): return {k:\
        \ round(100*v/total,2) for k,v in d.items()} if total else {}\nout={\"total\"\
        :total,\"by_sector\":pctmap(bx),\"by_country\":pctmap(cx),\"by_type\":pctmap(tx)}\n\
        thr={\"sector\":40.0,\"country\":70.0,\"single_vs_etf\":70.0}  # tweak as\
        \ you like\nwarnings=[]\nfor s,p in out[\"by_sector\"].items():\n    if p>thr[\"\
        sector\"]: warnings.append(f\"Sector {s} = {p}% (> {thr['sector']}%)\")\n\
        for c,p in out[\"by_country\"].items():\n    if p>thr[\"country\"]: warnings.append(f\"\
        Country {c} = {p}% (> {thr['country']}%)\")\nif out[\"by_type\"].get(\"EQUITY\"\
        ,0)>thr[\"single_vs_etf\"]:\n    warnings.append(f\"Single-name exposure =\
        \ {out['by_type'].get('EQUITY',0)}% (> {thr['single_vs_etf']}%)\")\nos.makedirs(\"\
        snapshots\", exist_ok=True)\nopen(\"snapshots/exposure.json\",\"w\").write(json.dumps({\"\
        exposure\":out,\"warnings\":warnings}, indent=2))\nPY\n"
    - uses: actions/upload-artifact@v4
      with:
        name: exposure
        path: snapshots/exposure.json
        retention-days: 7
    needs: precheck
    if: ${{ needs.precheck.outputs.ok == 'true' && github.ref == 'refs/heads/main'
      }}
