name: File Scheduler Europe

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Bypass time gate'
        required: false
        default: 'true'
        type: string

permissions:
  contents: read

jobs:
  call:
    uses: ./.github/workflows/universal_report_scheduler.yml
    secrets: inherit
    with:
      region: 'EU'
      timezone: 'Europe/London'
      enabled: 'true'
      force_run: ${{ inputs.force_run }}
      upload_artifacts: 'true'
