name: Deploy to Render (Web + Cron)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Web Deploy
        if: ${{ secrets.RENDER_WEB_SERVICE_ID && secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_WEB_SERVICE_ID }}/deploys"             -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"             -H "Content-Type: application/json"             -d '{}'

      - name: Trigger Render Cron Deploy
        if: ${{ secrets.RENDER_CRON_SERVICE_ID && secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_CRON_SERVICE_ID }}/deploys"             -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"             -H "Content-Type: application/json"             -d '{}'