name: Screener Quotes (Hourly)

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: vega-data
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build screener quotes
        run: |
          python workers/snapshots/screener_quotes.py
      - name: Commit quotes
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add data/screener_quotes.csv
          git commit -m "data: screener quotes $(date -u +%FT%TZ)" || echo "no changes"
          git push origin vega-data
