name: Color Guard Prep

on:
  workflow_dispatch:
  schedule:
    - cron: '23 13 * * 1-5'   # 6:23 AM PT
permissions: { contents: read }

concurrency:
  group: color-guard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs: { ok: ${{ steps.p.outputs.ok }} }
    steps:
      - uses: actions/checkout@v4
      - id: p
        uses: ./.github/actions/precheck

  prep:
    if: ${{ needs.precheck.outputs.ok == 'true' && github.ref == 'refs/heads/main' }}
    needs: precheck
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: pip install -r requirements.txt
      - name: Build guard snapshot (non-critical pulls)
        run: python modules/guards/color_guard_prep.py
      - name: Fetch news feed (non-critical)
        continue-on-error: true
        run: python modules/guards/fetch_news.py
