name: Econ Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: '27 13 * * 1-5'   # 6:27 AM PT
permissions: { contents: read }

concurrency:
  group: econ-calendar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs: { ok: ${{ steps.p.outputs.ok }} }
    steps:
      - uses: actions/checkout@v4
      - id: p
        uses: ./.github/actions/precheck

  render:
    if: ${{ needs.precheck.outputs.ok == 'true' && github.ref == 'refs/heads/main' }}
    needs: precheck
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: pip install -r requirements.txt
      - name: Build econ calendar
        run: python modules/calendar/build_calendar.py
